version: "3.7"

services:
  deno-backend:
    container_name: deno-api
    image: "deno-api:0.0.1"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - mongo
    volumes:
      - ./backend/:/usr/app/backend

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: deno-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mongoInit.js:/docker-entrypoint-initdb.d/mongoInit.js

  react-frontend:
    container_name: react-frontend
    command: npm start
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/app/frontend
      - ./frontend/node_modules
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

networks:
  deno: {}
